# Site settings
title: Windyland
header-img: img/home-bg.jpg
email: david@davidwho.me
description: "Thinking, Coding, Sharing"
baseurl: ""
url: "http:/davidwho.me"
twitter_username: DavidHu_iOS
github_username:  DavidHu0921


# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]