# Site settings
title: Windyland
header-img: img/home-bg.jpg
email: david@davidwho.me
description: "Let's happy coding!"
baseurl: ""
url: "http:/davidwho.me"
twitter_username: davdhu92
github_username:  davdhu92
facebook_username:  davdhu92

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]